### ISSUE TITLE
Export Location on Android

### ISSUE THREAD

**Issue by cubeDHS2017** [naoxio/inbreeze#47]
I tried exporting my data on android but could not find the json file on my phone.

**Comment by waozixyz** [comment]
@cubeDHS2017 Hi, it should default to the downloads folder, but i should check if all is still working.

what android version are you using?

**Comment by waozixyz** [comment]
Hi just checked you are right, i seem to have broken something on the last update

**Comment by waozixyz** [comment]
@cubeDHS2017 should be fixed again at v1.3.7
